
name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Release build
        run: |
          msbuild PFD_Editor.sln /t:clean /p:Configuration=Release

      - name: Debug build
        run: |
          msbuild PFD_Editor.sln /t:clean /p:Configuration=Debug
