
name: Test

on:
  push:
    branches: [ "master" ]
    paths-ignore: [ "badges" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Restore NuGet packages
        run: nuget restore PFD_Editor.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Debug build
        run: msbuild PFD_Editor.sln /p:Configuration=Debug /p:Platform="Any CPU"

      - name: Execute AltCover
        run: packages\altcover.8.6.68\tools\net472\altcover.exe /i="UnitTestProject/bin/Debug" /o="__Instrumented/UnitTestProject/bin/Debug" -l

      - name: UnitTest with Coverage
        run: '& "$(vswhere -property installationPath)\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" __Instrumented\UnitTestProject\bin\Debug\UnitTestProject.dll'

      - name: ReportGenerator
        run: packages\ReportGenerator.5.1.26\tools\net47\ReportGenerator.exe -reports:coverage.xml -targetdir:.\CoverageReport -reporttypes:'Html;MarkdownSummaryGithub;JsonSummary;Badges'

      - run: ls CoverageReport

      - name: Artifact coverage report
        uses: actions/upload-artifact@v3
        with:
          name: coverage-report
          path: .\CoverageReport

      - name: Artifact coverage.xml
        uses: actions/upload-artifact@v3
        with:
          name: coverage_xml
          path: ./coverage.xml

      - name: Add Coverage PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: CoverageReport/SummaryGithub.md

      - name: Push badges to master_badges branch
        if: github.event_name == 'push'
        run: |
          mkdir badges
          cp CoverageReport/badge_combined.svg badges/
          git config user.name auto-push
          git config user.email auto-push@example.com
          git add badges
          git commit -m "auto push from ci" || echo no commits
          git push
