
name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/NuGet/setup-nuget
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Restore NuGet packages
        run: nuget restore PFD_Editor.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Debug build
        run: msbuild PFD_Editor.sln /p:Configuration=Debug /p:Platform="Any CPU"
      - run: pwd
      - run: ls PFD_Editor
      - run: ls UnitTestProject
      - run: ls UnitTestProject\obj
      - run: ls UnitTestProject\obj\Debug

      - name: UnitTest
        run: |
          '& "$(vswhere -property installationPath)\Common7\IDE\mstest.exe" /testcontainer:UnitTestProject\obj\Debug\UnitTestProject.dll'

      - run: packages\altcover.8.6.68\tools\net472\altcover.exe
      - run: pwd
      - run: ls UnitTestProject
      - run: ls UnitTestProject\obj
      - run: ls UnitTestProject\obj\Debug
      - run: ls __Instrumented
      - run: ls __Instrumented\UnitTestProject
      - run: ls __Instrumented\UnitTestProject\obj
      - run: ls __Instrumented\UnitTestProject\obj\Debug
      - run: '& "$(vswhere -property installationPath)\Common7\IDE\mstest.exe" /testcontainer:__Instrumented\UnitTestProject\obj\Debug\UnitTestProject.dll'
