
name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - run:  '& "$(vswhere -property installationPath)\Common7\IDE\MSTest.exe" /help'

      - run: "vstest.console.exe /help"
