
name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      # https://github.com/NuGet/setup-nuget
      - name: Setup NuGet
        uses: nuget/setup-nuget@v1
        with:
          nuget-api-key: ${{ secrets.NuGetAPIKey }}
          nuget-version: '5.x'

      - name: Restore NuGet packages
        run: nuget restore PFD_Editor.sln

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Debug build
        run: |
          msbuild PFD_Editor.sln /t:clean /p:Configuration=Debug

      - run: cd ..\UnitTestProject\bin\Debug
      - run: altcover.exe
      - run: cd ./__Instrumented
      - run: '& "$(vswhere -property installationPath)\Common7\IDE\mstest.exe" /testcontainer:UnitTestProject.dll'

#      - name: UnitTest
#        run: |
#          '& "$(vswhere -property installationPath)\Common7\IDE\mstest.exe" /testcontainer:UnitTestProject\bin\Debug\UnitTestProject.dll'
