
name: Test

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Setup nuget
        uses: warrenbuckley/Setup-Nuget@v1

      - name: Debug build
        run: |
          msbuild PFD_Editor.sln /t:clean /p:Configuration=Debug

      - name: UnitTest
        run: |
          '& "$(vswhere -property installationPath)\Common7\IDE\mstest.exe" /testcontainer:UnitTestProject\bin\Debug\UnitTestProject.dll'
